import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { DevicePreview } from "@/components/lab/device-preview";
import { entries, getEntry, previewHref } from "@/registry/entries";

export function generateStaticParams() { return entries.map(entry => ({ category: entry.category, slug: entry.slug })); }
export async function generateMetadata({ params }: { params: Promise<{ category: string; slug: string }> }): Promise<Metadata> { const { category, slug } = await params; const entry = getEntry(category, slug); return { title: entry ? `${entry.id} — ${entry.title}` : "Exemplo", description: entry?.description, alternates: { canonical: `/${category}/${slug}/` }, openGraph: { title: entry ? `${entry.id} — ${entry.title}` : "Exemplo", description: entry?.description } }; }
export default async function DemoPage({ params }: { params: Promise<{ category: string; slug: string }> }) { const { category, slug } = await params; const entry = getEntry(category, slug); if (!entry) notFound(); return <div className="shell"><div className="page-title"><Link className="eyebrow" href={`/category/${category}/`}>← Voltar para a categoria</Link><h1>{entry.title}</h1><p className="muted"><strong>{entry.id}</strong> · {entry.description}</p></div><DevicePreview src={previewHref(entry)} title={entry.title} /><div className="details"><section className="details-panel"><h2>Sobre este exemplo</h2><ul>{entry.features.map(feature => <li key={feature}>{feature}</li>)}</ul><div className="tag-row">{entry.tags.map(tag => <span className="tag" key={tag}>{tag}</span>)}</div></section><section className="details-panel"><h2>Para desenvolvedores</h2><p className="muted">Criado com {entry.technologies.join(" e ")}. Responsivo: {entry.responsive ? "sim" : "não"}. Modo escuro: {entry.darkMode ? "sim" : "não"}.</p><p className="muted">Código: <a href={`https://github.com/Alexandre458/alexandre-ui-lab/blob/main/${entry.sourcePath}`} target="_blank" rel="noopener noreferrer">{entry.sourcePath} ↗</a></p></section></div></div>; }
