"use client";

import { useState } from "react";
import { money, parseDecimal } from "./local-values";
const collections = [{ id: "ceramica", title: "Cerâmica Objetos", price: 189 }, { id: "poster", title: "Pôsteres Gráficos", price: 96 }, { id: "textil", title: "Têxtil", price: 240 }, { id: "moveis", title: "Mobiliário", price: 1290 }, { id: "fotografia", title: "Fotografia", price: 150 }];
const delivery = [{ id: "standard", title: "Padrão", days: "5–7 dias úteis", extra: 0 }, { id: "express", title: "Expresso", days: "2–3 dias úteis", extra: 39 }];

export default function AssistedFieldDesignStore() {
  const [collectionId, setCollectionId] = useState(""); const [rawQuantity, setRawQuantity] = useState("1"); const [deliveryId, setDeliveryId] = useState("standard"); const [confirmed, setConfirmed] = useState(false);
  const collection = collections.find(item => item.id === collectionId); const format = delivery.find(item => item.id === deliveryId)!;
  const quantity = parseDecimal(rawQuantity); const validQuantity = quantity !== null && Number.isInteger(quantity) && quantity >= 1 && quantity <= 8;
  const ready = Boolean(collection) && validQuantity;
  const subtotal = ready ? collection!.price * quantity! : 0;
  return <section className="revision-demo order-demo" aria-label="Pedido de coleção"><div className="order-canvas">
    <header><span className="demo-kicker">DESIGN STORE / 017</span><h1>O preço.<br /><em>Parte por parte.</em></h1></header><div className="order-layout">
      <fieldset className="order-options" disabled={confirmed}><legend>Monte seu pedido local</legend><label>Coleção<select value={collectionId} onChange={event => setCollectionId(event.target.value)}><option value="">Escolha sua coleção</option>{collections.map(item => <option key={item.id} value={item.id}>{item.title}</option>)}</select></label><label htmlFor="order-quantity">Quantidade</label><div className="order-stepper"><button type="button" aria-label="Diminuir quantidade" disabled={!validQuantity || quantity! <= 1} onClick={() => setRawQuantity(String(quantity! - 1))}>−</button><input id="order-quantity" inputMode="numeric" value={rawQuantity} aria-invalid={!validQuantity} aria-describedby="order-quantity-help" onChange={event => setRawQuantity(event.target.value)} /><button type="button" aria-label="Aumentar quantidade" disabled={!validQuantity || quantity! >= 8} onClick={() => setRawQuantity(String(quantity! + 1))}>+</button></div><p id="order-quantity-help">De 1 a 8 itens, sempre em unidades inteiras.</p><fieldset className="order-delivery"><legend>Formato de entrega</legend>{delivery.map(item => <label key={item.id}><input type="radio" name="order-delivery" checked={deliveryId === item.id} onChange={() => setDeliveryId(item.id)} /><span><strong>{item.title}</strong><small>{item.days} · +{money(item.extra)}</small></span></label>)}</fieldset></fieldset>
      <aside className="order-receipt"><span className="demo-kicker">RECIBO DEMONSTRATIVO</span><h2>{collection?.title || "Escolha uma coleção"}</h2><dl><div><dt>Preço por item</dt><dd>{collection ? money(collection.price) : "—"}</dd></div><div><dt>Quantidade</dt><dd>{validQuantity ? `${quantity} itens` : "Inválida"}</dd></div><div><dt>Subtotal</dt><dd>{ready ? money(subtotal) : "—"}</dd></div><div><dt>Entrega · {format.title}</dt><dd>{money(format.extra)}</dd></div><div className="order-total"><dt>Total</dt><dd>{ready ? money(subtotal + format.extra) : "—"}</dd></div></dl><p role="status">{confirmed ? "Pedido confirmado nesta tela. Revise para editar." : "Confira as parcelas antes de confirmar."}</p>{confirmed && <p className="order-reference">Código local: DS-17-{collectionId.toUpperCase()}-{quantity}-{deliveryId.toUpperCase()}</p>}{confirmed ? <button type="button" onClick={() => setConfirmed(false)}>Revisar pedido</button> : <button type="button" disabled={!ready} onClick={() => { if (ready) setConfirmed(true); }}>Confirmar pedido</button>}<button type="button" onClick={() => { setCollectionId(""); setRawQuantity("1"); setDeliveryId("standard"); setConfirmed(false); }}>Novo pedido</button></aside>
    </div><p className="revision-note">Uma simulação de custo. Nenhuma compra, cobrança ou entrega acontece.</p>
  </div></section>;
}
