"use client";

import { useState } from "react";
import { ArrowDownRight, ArrowUpRight, Menu, X } from "lucide-react";

export default function AtelierHero() {
  const [menuOpen, setMenuOpen] = useState(false);
  return <section className="demo-hero"><header className="atelier-header"><span className="atelier-brand">SOMA<span>®</span></span><button className="atelier-menu" type="button" onClick={() => setMenuOpen(!menuOpen)} aria-expanded={menuOpen} aria-label={menuOpen ? "Fechar menu" : "Abrir menu"}>{menuOpen ? <X size={23} /> : <Menu size={23} />}</button><nav className={menuOpen ? "open" : ""} aria-label="Navegação da demonstração"><a href="#about" onClick={() => setMenuOpen(false)}>Sobre</a><a href="#work" onClick={() => setMenuOpen(false)}>Projetos</a><a href="#contact" onClick={() => setMenuOpen(false)}>Contato</a></nav></header><div className="atelier-body"><div className="atelier-topline"><span>ESTÚDIO INDEPENDENTE<br />SÃO PAULO · BRASIL</span><span>DESIGN / DIREÇÃO / EXPERIÊNCIA</span></div><div className="atelier-main"><div><span className="demo-kicker">IDEIAS QUE PERMANECEM</span><h1>Forma.<br /><em>Sentido.</em><br />Futuro.</h1><a className="atelier-cta" href="#work">Descubra nosso trabalho <ArrowUpRight size={21} /></a></div><div className="atelier-composition" aria-hidden="true"><span className="atelier-orbit" /><span className="atelier-disc" /><span className="atelier-label">SOMA<br />01—26</span></div></div><div className="atelier-bottom"><a href="#about">Continue explorando <ArrowDownRight size={18} /></a><span>CRIAMOS O QUE AINDA NÃO EXISTE.</span></div></div><div id="about" className="atelier-extra"><h2>Um novo olhar para o essencial.</h2><p>Experiências digitais e identidades que unem clareza, caráter e propósito.</p></div><div id="work" className="atelier-extra alt"><h2>Projetos com intenção.</h2><p>Uma seleção fictícia para demonstrar navegação local neste conceito.</p></div><div id="contact" className="atelier-extra"><h2>Vamos conversar.</h2><p>Esta página é uma demonstração visual sem formulário ou envio de dados.</p></div></section>;
}
