export type Entry = {
  id: string; challengeNumber: number; title: string; description: string;
  category: string; subcategory: string; slug: string; tags: string[];
  technologies: string[]; responsive: boolean; darkMode: boolean;
  difficulty: "Iniciante" | "Intermediário" | "Avançado";
  createdAt: string; features: string[]; sourcePath: string;
  thumbnail: "button" | "input" | "card" | "login" | "hero" | "fundamentals";
};

export const categories = [
  { slug: "buttons", title: "Botões", description: "Ações pequenas, expressivas e acessíveis." },
  { slug: "inputs", title: "Campos", description: "Entradas claras para experiências melhores." },
  { slug: "cards", title: "Cards", description: "Informação com composição e personalidade." },
  { slug: "login", title: "Login", description: "Interfaces de acesso prontas para explorar." },
  { slug: "hero", title: "Hero", description: "Primeiras impressões que comunicam valor." },
  { slug: "fundamentals", title: "Fundamentos", description: "Interações essenciais para experiências completas." },
] as const;

export const entries: Entry[] = [
  { id: "FUND-0022", challengeNumber: 22, title: "Cartão de alergênicos de receita", description: "Uma pessoa seleciona uma receita e visualiza os alergênicos presentes nos ingredientes, expandindo detalhes sem ocultar a composição completa.", category: "fundamentals", subcategory: "Form Fields", slug: "cartao-de-alergenicos-de-receita", tags: ["allergen", "food", "recipe", "health", "alergenico", "receita", "alimento"], technologies: ["React", "CSS"], responsive: true, darkMode: false, difficulty: "Iniciante", createdAt: "2026-10-06", features: ["Seleção de receita", "Expansão de alergênicos", "Visualização progressiva", "Ausência declarada"], sourcePath: "src/demos/fundamentals/cartao-de-alergenicos-de-receita.tsx", thumbnail: "fundamentals" },
  { id: "FUND-0020", challengeNumber: 20, title: "Editor de identificador de branch", description: "Uma pessoa escreve um nome de branch em uma linha, vê a prévia normalizada e o diagnóstico local de nomes reservados e colisões antes de digitar qualquer comando git.", category: "fundamentals", subcategory: "Form Fields", slug: "editor-de-identificador-de-branch", tags: ["branch", "identificador", "normalização", "colisão", "git", "sandbox"], technologies: ["React", "CSS"], responsive: true, darkMode: true, difficulty: "Iniciante", createdAt: "2026-10-04", features: ["Prévia normalizada em tempo real", "Diagnóstico de nome reservado e colisão local", "Correção, desfazer e reinicio do sandbox"], sourcePath: "src/demos/fundamentals/editor-de-identificador-de-branch.tsx", thumbnail: "fundamentals" },
  { id: "FUND-0021", challengeNumber: 21, title: "Ficha de fóssil com escala", description: "Uma pessoa mede um objeto (fóssil) e compara sua escala com ferramentas conhecidas para entender a necessidade de quantidade.", category: "fundamentals", subcategory: "Form Fields", slug: "ficha-de-fossil-com-escala", tags: ["scale", "measurement", "comparison", "fossils", "fóssil", "escala", "medida", "comparação"], technologies: ["React", "CSS"], responsive: true, darkMode: false, difficulty: "Iniciante", createdAt: "2026-10-05", features: ["Medida real vs ferramenta", "Cálculo de quantidade", "Visualização de escala", "Comparação de comprimento"], sourcePath: "src/demos/fundamentals/ficha-de-fossil-com-escala.tsx", thumbnail: "fundamentals" },
  { id: "FUND-0019", challengeNumber: 19, title: "Bilheteria assistida com validação cruzada", description: "Uma pessoa conclui um pedido nominal de ingressos e entende qual campo impede a geração; a programação e o bilhete são totalmente locais.", category: "fundamentals", subcategory: "Form Fields", slug: "assisted-field-cultural-producer", tags: ["formulario", "validacao", "bilheteria", "cultural", "eventos", "produtora"], technologies: ["React", "CSS"], responsive: true, darkMode: false, difficulty: "Iniciante", createdAt: "2026-10-04", features: ["Programação fictícia", "Campos com dicas e limites", "Bilhete com código local"], sourcePath: "src/demos/fundamentals/assisted-field-cultural-producer.tsx", thumbnail: "fundamentals" },
  { id: "FUND-0018", challengeNumber: 18, title: "Leitura ambiental com unidade e meta", description: "Uma equipe registra um valor acumulado de uma única iniciativa e verifica unidade, limite e atingimento da meta fictícia.", category: "fundamentals", subcategory: "Form Fields", slug: "campos-assistidos-plataforma-ambiental", tags: ["formulario", "validacao", "acessibilidade", "ambiental", "metas"], technologies: ["React", "CSS"], responsive: true, darkMode: true, difficulty: "Iniciante", createdAt: "2026-05-14", features: ["Unidade por iniciativa", "Árvores inteiras", "Progresso da meta"], sourcePath: "src/demos/fundamentals/assisted-field-plataforma-ambiental.tsx", thumbnail: "fundamentals" },
  { id: "BTN-001", challengeNumber: 1, title: "Confirmação reversível de uma ação", description: "Uma pessoa precisa reconhecer o término de uma ação pequena e poder voltar ao estado anterior sem disparar outra execução acidental.", category: "buttons", subcategory: "Actions", slug: "confirmation-button", tags: ["button", "feedback", "loading", "botão", "confirmação"], technologies: ["React", "CSS"], responsive: true, darkMode: false, difficulty: "Iniciante", createdAt: "2026-09-16", features: ["Confirmação única", "Desfazer explícito", "Espera com limpeza"], sourcePath: "src/demos/buttons/confirmation-button.tsx", thumbnail: "button" },
  { id: "INPUT-001", challengeNumber: 2, title: "Diagnóstico e correção explícita de e-mail", description: "Uma pessoa revisa um endereço antes de continuar; precisa distinguir formato inválido de uma possível troca de letras no domínio.", category: "inputs", subcategory: "Form Fields", slug: "smart-email-field", tags: ["input", "validation", "email", "validação", "e-mail", "campo"], technologies: ["React", "CSS"], responsive: true, darkMode: false, difficulty: "Iniciante", createdAt: "2026-09-16", features: ["Sugestão de domínio", "Correção por escolha", "Recibo local"], sourcePath: "src/demos/inputs/smart-email-field.tsx", thumbnail: "input" },
  { id: "CARD-001", challengeNumber: 3, title: "Coleção editorial com salvar e inspecionar", description: "Uma pessoa explora uma edição de design e precisa saber se salvou a edição e o que ela contém.", category: "cards", subcategory: "Editorial", slug: "editorial-collection-card", tags: ["card", "editorial", "collection", "coleção"], technologies: ["React", "CSS"], responsive: true, darkMode: false, difficulty: "Iniciante", createdAt: "2026-09-16", features: ["Favorito por edição", "Conteúdo expansível", "Coleção local"], sourcePath: "src/demos/cards/editorial-collection-card.tsx", thumbnail: "card" },
  { id: "LOGIN-001", challengeNumber: 4, title: "Acesso demonstrativo a um workspace", description: "Uma pessoa experimenta a ergonomia de uma tela de acesso sem criar sessão, autenticação ou persistência real.", category: "login", subcategory: "Auth", slug: "workspace-login", tags: ["login", "auth", "form", "saas", "workspace"], technologies: ["React", "CSS"], responsive: true, darkMode: true, difficulty: "Intermediário", createdAt: "2026-09-16", features: ["Validação derivada", "Senha reversível", "Limpeza de credenciais"], sourcePath: "src/demos/login/workspace-login.tsx", thumbnail: "login" },
  { id: "HERO-001", challengeNumber: 5, title: "Abertura editorial com navegação de seções", description: "Uma pessoa conhece um estúdio e se orienta entre proposta, projetos e contato sem abandonar a página demonstrativa.", category: "hero", subcategory: "Landing", slug: "atelier-hero", tags: ["hero", "landing", "editorial", "atelier", "estúdio"], technologies: ["React", "CSS"], responsive: true, darkMode: false, difficulty: "Intermediário", createdAt: "2026-09-16", features: ["Destinos de seção", "Escape no menu", "Navegação móvel"], sourcePath: "src/demos/hero/atelier-hero.tsx", thumbnail: "hero" },
  { id: "FUND-0006", challengeNumber: 6, title: "Caderno de prática com pré-requisitos", description: "Uma estudante de pintura acompanha evidências de prática; avanço depende de trabalho marcado por ela, não de tempo decorrido.", category: "fundamentals", subcategory: "Contextual Actions", slug: "contextual-action-button", tags: ["button", "contextual", "progress", "education", "escola", "criativa", "prática"], technologies: ["React", "CSS"], responsive: true, darkMode: false, difficulty: "Iniciante", createdAt: "2026-09-17", features: ["Etapas com pré-requisitos", "Reabertura em cascata", "Progresso manual"], sourcePath: "src/demos/fundamentals/contextual-action-button.tsx", thumbnail: "fundamentals" },
  { id: "FUND-0007", challengeNumber: 7, title: "Reserva local de peças com estoque", description: "Uma curadora separa peças disponíveis e precisa entender imediatamente o limite de estoque e a quantidade separada.", category: "fundamentals", subcategory: "Contextual Actions", slug: "contextual-action-store", tags: ["button", "contextual", "order", "design", "loja", "estoque"], technologies: ["React", "CSS"], responsive: true, darkMode: false, difficulty: "Iniciante", createdAt: "2026-09-18", features: ["Estoque finito", "Reserva por unidade", "Devolução por linha"], sourcePath: "src/demos/fundamentals/contextual-action-store.tsx", thumbnail: "fundamentals" },
  { id: "FUND-0008", challengeNumber: 8, title: "Comparador de emissões por base equivalente", description: "Uma analista compara dois períodos e escolhe a base do indicador antes de interpretar a mudança.", category: "fundamentals", subcategory: "Contextual Actions", slug: "contextual-action-environmental", tags: ["button", "contextual", "indicator", "environmental", "ambiental", "emissões"], technologies: ["React", "CSS"], responsive: true, darkMode: true, difficulty: "Iniciante", createdAt: "2026-09-21", features: ["Base por unidade", "Variação derivada", "Denominador zero"], sourcePath: "src/demos/fundamentals/contextual-action-environmental.tsx", thumbnail: "fundamentals" },
  { id: "FUND-0009", challengeNumber: 9, title: "Mapa de lugares para uma sessão cultural", description: "Uma pessoa escolhe lugares de uma sessão teatral e precisa ver localização, disponibilidade e custo antes de confirmar.", category: "fundamentals", subcategory: "Contextual Actions", slug: "contextual-action-cultural-producer", tags: ["button", "contextual", "event", "tickets", "cultural", "produtora", "assentos"], technologies: ["React", "CSS"], responsive: true, darkMode: true, difficulty: "Iniciante", createdAt: "2026-09-22", features: ["Mapa de assentos", "Limite de seleção", "Reserva revisável"], sourcePath: "src/demos/fundamentals/contextual-action-cultural-producer.tsx", thumbnail: "fundamentals" },
  { id: "FUND-0010", challengeNumber: 10, title: "Quadro de release com dependências", description: "Uma equipe revisa os requisitos de uma release e observa o impacto de publicar e reverter em ambiente fictício.", category: "fundamentals", subcategory: "Contextual Actions", slug: "contextual-action-software-team", tags: ["button", "contextual", "deploy", "release", "software"], technologies: ["React", "CSS"], responsive: true, darkMode: true, difficulty: "Iniciante", createdAt: "2026-09-23", features: ["Checklist de release", "Versão e rollback", "Histórico local"], sourcePath: "src/demos/fundamentals/contextual-action-software-team.tsx", thumbnail: "fundamentals" },
  { id: "FUND-0011", challengeNumber: 11, title: "Agenda preventiva com horários disponíveis", description: "Uma pessoa agenda uma conversa preventiva simulada escolhendo dia e horário com disponibilidade explícita; não há triagem médica.", category: "fundamentals", subcategory: "Form Fields", slug: "assisted-field-preventive-clinic", tags: ["input", "validation", "form", "health", "clinic", "clínica", "horários", "agenda"], technologies: ["React", "CSS"], responsive: true, darkMode: false, difficulty: "Iniciante", createdAt: "2026-09-24", features: ["Disponibilidade por dia", "Horário ocupado", "Agenda revisável"], sourcePath: "src/demos/fundamentals/assisted-field-preventive-clinic.tsx", thumbnail: "fundamentals" },
  { id: "FUND-0012", challengeNumber: 12, title: "Programa de ambientes com limite de área", description: "Uma arquiteta monta um programa espacial conceitual e compara demanda dos ambientes ao limite do projeto.", category: "fundamentals", subcategory: "Form Fields", slug: "assisted-field-architecture-studio", tags: ["input", "validation", "form", "architecture", "project", "arquitetura", "áreas"], technologies: ["React", "CSS"], responsive: true, darkMode: false, difficulty: "Iniciante", createdAt: "2026-09-25", features: ["Áreas por ambiente", "Capacidade e excesso", "Diagrama proporcional"], sourcePath: "src/demos/fundamentals/assisted-field-architecture-studio.tsx", thumbnail: "fundamentals" },
  { id: "FUND-0013", challengeNumber: 13, title: "Livro-caixa com centavos e estorno", description: "Uma pessoa experimenta um registro financeiro fictício e entende como cada lançamento altera o saldo; não é recomendação financeira.", category: "fundamentals", subcategory: "Form Fields", slug: "assisted-field-financial-platform", tags: ["input", "validation", "form", "finance", "transaction", "financeira", "transações", "livro-caixa", "valor"], technologies: ["React", "CSS"], responsive: true, darkMode: false, difficulty: "Iniciante", createdAt: "2026-09-26", features: ["Centavos inteiros", "Saldo derivado", "Estorno com histórico"], sourcePath: "src/demos/fundamentals/assisted-field-financial-platform.tsx", thumbnail: "fundamentals" },
  { id: "FUND-0014", challengeNumber: 14, title: "Diário de leitura com spoiler controlado", description: "Uma leitora compõe uma ficha de leitura e controla quando uma anotação sensível se torna visível na própria demo.", category: "fundamentals", subcategory: "Form Fields", slug: "assisted-field-reading-community", tags: ["input", "validation", "form", "reading", "community", "leitura", "comunidade"], technologies: ["React", "CSS"], responsive: true, darkMode: false, difficulty: "Iniciante", createdAt: "2026-09-27", features: ["Avaliação por teclado", "Anotação com spoiler", "Ficha revisável"], sourcePath: "src/demos/fundamentals/assisted-field-reading-community.tsx", thumbnail: "fundamentals" },
  { id: "FUND-0015", challengeNumber: 15, title: "Comparador de trajetos por velocidade", description: "Uma pessoa compara três meios de deslocamento em uma simulação sem mapa ou tráfego real.", category: "fundamentals", subcategory: "Form Fields", slug: "assisted-field-mobility-brand", tags: ["input", "validation", "form", "mobility", "route", "mobilidade", "rotas"], technologies: ["React", "CSS"], responsive: true, darkMode: true, difficulty: "Iniciante", createdAt: "2026-09-28", features: ["Comparação de velocidades", "Duração arredondada", "Validação de terminais"], sourcePath: "src/demos/fundamentals/assisted-field-mobility-brand.tsx", thumbnail: "fundamentals" },
  { id: "FUND-0016", challengeNumber: 16, title: "Planejador de meta de estudos por capacidade", description: "Uma estudante escolhe trilha e frequência e descobre se a meta cabe no período de estudo fictício.", category: "fundamentals", subcategory: "Form Fields", slug: "assisted-field-creative-school", tags: ["input", "validation", "form", "education", "school", "escola", "criativa", "estudos"], technologies: ["React", "CSS"], responsive: true, darkMode: false, difficulty: "Iniciante", createdAt: "2026-09-29", features: ["Capacidade semanal", "Meta incompatível", "Ajuste explícito"], sourcePath: "src/demos/fundamentals/assisted-field-creative-school.tsx", thumbnail: "fundamentals" },
  { id: "FUND-0017", challengeNumber: 17, title: "Pedido de coleção com decomposição de preço", description: "Uma pessoa configura um pedido cenográfico e consegue reconstruir o total antes de confirmar.", category: "fundamentals", subcategory: "Form Fields", slug: "assisted-field-design-store", tags: ["input", "validation", "form", "design", "store", "loja", "coleção"], technologies: ["React", "CSS"], responsive: true, darkMode: false, difficulty: "Iniciante", createdAt: "2026-10-01", features: ["Preço discriminado", "Quantidade limitada", "Pedido revisável"], sourcePath: "src/demos/fundamentals/assisted-field-design-store.tsx", thumbnail: "fundamentals" },
];

export function getEntry(category: string, slug: string) { return entries.find(entry => entry.category === category && entry.slug === slug); }
export function entryHref(entry: Entry) { return `/${entry.category}/${entry.slug}/`; }
export function previewHref(entry: Entry) { return `/preview/${entry.category}/${entry.slug}/`; }
export function searchEntries(query: string, category = "all") {
  const term = query.trim().toLocaleLowerCase("pt-BR");
  return entries.filter(entry => (category === "all" || entry.category === category) && (!term || [entry.id, entry.title, entry.description, entry.category, entry.subcategory, ...entry.tags].join(" ").toLocaleLowerCase("pt-BR").includes(term)));
}
